"""empty message

Revision ID: 294bc939c6f0
Revises: b7f94405d38d
Create Date: 2024-11-27 23:10:32.844008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294bc939c6f0'
down_revision = 'b7f94405d38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assessment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('module_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('deadline', sa.DATETIME(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
